apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pythondzone-dc
  labels:
    app: pythondzone
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: pythondzone     
    spec:
      containers:
      - name: pythondzone-ctr
        image: sreedocker123/pythondzone:latest   
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 8000
